# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "fe.fullname" . }}
#   labels:
#     {{- include "fe.labels" . | nindent 4 }}
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: TCP
#       name: http
#   selector:
#     {{- include "fe.selectorLabels" . | nindent 4 }}

apiVersion: v1
kind: Service
metadata:
  name: craftista-fe-svc
  namespace: craftista

spec:
  selector:
    app: craftista-fe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
